### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Daksh-Goel12** [hkirat/gsoc-good-first-issues#14]
I can make the readme visually more appealing and can update the list. I am also a GSSoC'23 contributor. I can add more contents in readme. @hkirat

**Comment by rajeevkumar504** [comment]
> I can make the readme visually more appealing and can update the list. I am also a GSSoC'23 contributor. I can add more contents in readme. @hkirat

I also want to do that so can it's all up to @hkirat  bhiya, if they assign it to us so I like to work on this issue together with you.
