### ISSUE TITLE
Jitsi will not be taking part in GSOC this year

### ISSUE THREAD

**Issue by Manice18** [hkirat/gsoc-good-first-issues#2]
I was contributing to jitsi and asked regarding GSOC to one of the maintainers of the organization to which he said that they won't be taking part this year in GSOC. Here is the screenshot of the convo:

![jitsi](https://user-images.githubusercontent.com/91601706/216784357-d5d95e06-5163-4947-802b-74f28908d63d.png)

**Comment by harshit-paneri** [comment]
Yes, [Jitsi ](https://github.com/jitsi)is not taking part in GSOC 23
![image](https://user-images.githubusercontent.com/82382478/216785930-f844a5e1-b432-4a8e-8576-0093360de008.png)

**Comment by alokVerma749** [comment]
Matrix Foundation will also not offer internships around the matrix.org website as part of GSoC

**Comment by saumyaborwankar** [comment]
are the others confirmed to take part in gsoc 23?
